# Generated by Django 3.2.5 on 2021-07-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_bookreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="user_profile_photos"
            ),
        ),
    ]
